FROM ubuntu:18.04

MAINTAINER Aymen Ben Othmen <aymen.othmen@wundermobility.com>

# Set a docker label to advertise multi-model support on the container
# LABEL com.amazonaws.sagemaker.capabilities.multi-models=true
# Set a docker label to enable container to use SAGEMAKER_BIND_TO_PORT environment variable if present
LABEL com.amazonaws.sagemaker.capabilities.accept-bind-to-port=true

# Install necessary dependencies for MMS and SageMaker Inference Toolkit
RUN apt-get update
RUN apt-get -y install --no-install-recommends \
    build-essential \
    ca-certificates \
    openjdk-8-jdk-headless \
    python3-dev \
    curl \
    vim \
    nginx

# installing git in the previous command (with other packages) fails.
RUN apt-get -y install git libgl1-mesa-glx libglib2.0-0

RUN rm -rf /var/lib/apt/lists/*
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python3 get-pip.py
RUN apt-get clean

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
RUN update-alternatives --install /usr/local/bin/pip pip /usr/local/bin/pip3 1

RUN pip3 --no-cache-dir install \
        torch \
        torchvision \
        opencv-python \
        pillow \
        numpy \
        scipy \
        pandas \
        boto3 \
        matplotlib \
        PyYAML \
        flask \
        gevent \
        Cython \
        tqdm \
        gunicorn

# todo: use env variable to download images from S3 instead.
#COPY images/00001.jpg /opt/images/00001.jpg
COPY aws/ /root/.aws

RUN git clone https://github.com/ultralytics/yolov5.git
RUN mv yolov5/ /opt/program

RUN rm -rf /root/.cache

COPY program/ /opt/program

ENV PATH="/opt/program:${PATH}"

RUN chmod 755 /opt/program
WORKDIR /opt/program
RUN chmod 755 serve

# Uncomment next lines to be able to run docker locally.
# On AWS, SageMaker will do the next steps automatically: get model artifacts from s3 and uncompress them.
#COPY ml/model.tar.gz .
#RUN mkdir -p /opt/ml/model
#RUN tar -zxvf model.tar.gz -C /opt/ml/model
#RUN rm model.tar.gz

CMD ["serve"]
