version: '3.9'

services:
    vehicle-detection:
        image: wunder-brain/vehicle-detection-gpu:dev-latest
        container_name: vehicle_detection_gpu_dev
        volumes:
            - type: bind
              source: ./ml
              target: /opt/ml
            - type: bind
              source: ./program
              target: /opt/program
        build:
            args:
                ENV: "dev"
                BASE_IMAGE: "wunder-brain/cuda-base"
                PYTHON_VER: '3.8'
                TEST_S3_BUCKET: 'wb-inference-data-exp'
                MAX_MODEL_SERVER_WORKERS: 2
                DEBUG_MODE: 'True'
        depends_on:
            - cuda-base
        deploy:
            replicas: 1
        working_dir: /opt/program
#        entrypoint: ["/bin/bash"]
        command: [ ]
