version: '3.9'

# test environment is very similar to prod and intended to be deployed to AWS fleetbird-experimental.
services:
    vehicle-detection:
        image: wunder-brain/vehicle-detection-gpu:test-latest
        container_name: vehicle_detection_gpu_test
        build:
            args:
                ENV: "test"
        environment:
            TEST_S3_BUCKET: 'wb-inference-data-exp'
            MAX_MODEL_SERVER_WORKERS: 32
